[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
dhukuti_program = "FrVMUmF1maCCiCZaVAkGn9mT69kQ5Hbgd9sUvzfmsgvs"

[programs.localnet]
dhukuti_program = "FrVMUmF1maCCiCZaVAkGn9mT69kQ5Hbgd9sUvzfmsgvs"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
